version: '3'
services:
  frontend:
    build:
      context: ./demo-app-urltobegin-1
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000

  backend:
    build:
      context: ./demo-app-express-backend
      dockerfile: Dockerfile
    environment:
      - DB_PATH=/data/database.db 
    env_file:
      - .env
    ports:
      - "3002:3002"
    volumes:
      - db_data:/data

volumes:
  db_data: